### ISSUE TITLE
AuthN: Openstack Keystone Password Auth

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/commissaire-http#21]
@intlabs noted it would be nice to have [Openstack Keystone](http://docs.openstack.org/developer/keystone/http-api.html) as a backend for authn.

See [httpauthclientcert.py](https://github.com/projectatomic/commissaire-http/blob/master/src/commissaire_http/authentication/httpauthclientcert.py) for a good starting point for how the authentication plugin code works.

**Comment by gbraad** [comment]
I'll have a look

**Comment by ashcrow** [comment]
@gbraad nice! @intlabs is also interested in this one. If possible you guys may be able to tackle different work areas and work together.

**Comment by gbraad** [comment]
I haven't put a lot of thought into it yet, as I first wanted to be sure Keystone was able to authenticate. I have a commit: https://github.com/gbraad/commissaire-http/commit/2772d45144fcc32810bf549497f8b0d850ae6499 which uses a hard-coded user.

are we going to use the basic authentication parameters to perform the login against Keystone using the password method?

**Comment by ashcrow** [comment]
@gbraad that looks like a good start! I'm not that familiar with the different types of authN in keystone but I'd say that user/pass via basic auth should be supported. Other mechanisms could be supported as well in their own classes. For example, if there is a keystone bearer token system that is commonly used one could create ``KeystoneBearerTokenAuth``.

@intlabs chime in as well!

**Comment by gbraad** [comment]
Should rename this to match: keystonepasswordauth.py

**Comment by intlabs** [comment]
@gbraad Hello! :)

I've looked at your code and it looks like a great start - though it's not the approach I was thinking of, it's much simpler. I was thinking of using [keystonemiddleware](http://docs.openstack.org/developer/keystonemiddleware/middlewarearchitecture.html) to let Commissaire operate as a fully fledged OpenStack service, with an entry in the Keystone Service Catalog - which would have the advantage of permitting any possible keystone auth method; and make it possible for Commissaire to do things like request certificates from Barbican for hosts. For this to work, I was going to map Keystone Projects 1:1 with Commissaire networks and clusters to make things simpler at first.

Why do this?
My motivation for doing things this way is because of the [Harbor](https://github.com/portdirect/harbor)  project I'm working on: I want users to be able to extend their OpenStack Cloud to arbitrary devices/servers: essentially as a replacement/compliment to Ironic that would enable a user to start a server running any flavor of Atomic Linux - and then register that node with Commissaire which would then provision as follows:

- Run ansible deployment:
  1. Generate/Check Keystone domain for users service accounts (nova, neutron etc)
  2. Generate/Check Keystone accounts for users service domain.
  3. Generate/Check Nova Cell for users domain.
  4. Generate/Check Certs for Kube and OpenStack services (via Barbican/certmonger)
  5. Work out most appropriate strategy to link node to Overcloud (ipsec if going over internet/ports for SSH/Geneve)
  6. Register new EP's with services as required.
  7. Update host to tree with kernel providing required OvS support
  9. Deploy Kubernetes, with Keystone Auth, Neutron/OVN CNI and Cinder/Manila volumes
  10. Label nodes appropriately.
  11.  Deploy required OpenStack Services via Kube (Neutron as a minimum) for users domain/cell.
- Let user go 'wow' I just extended my OpenStack cloud to 'X' with a similar user experience to setting up a chomecast, which opens up a whole world of use cases; from traditional hybrid cloud to things like [OpenCORD](http://opencord.org/), and IoT hubs (when are we gonna get Atomic on ARM? :-) )

By keeping user added hypervisors/nodes in their own domains, with totally separate service accounts, and using federated keystone auth this would allow a single "OverCloud" to manage untrusted endpoints; and manage both K8s and OpenStack services via Horizon.

For my use case, I expect federated keystone (behind apache with mod_mellon and getting user details via headers, before reaching out to keystone to map to the appropriate project/domain) to be the primary way end users will interact with Commissaire - which would then create a token that could be passed to the Commissaire Inspector for use within its Ansible Playbooks.

Though this sounds drastic, the only change required (outside of the auth module) would be adding a mechanism for transferring the trust token generated from the Commissaire Server to the Inspector (just like SHH keys are atm), a new/modified set of Ansible Playbooks, and the ability to map users to networks and clusters (as described would not require a real RBAC model).

I don't think it would be viable to extend the (perfectly valid) method gbraad's taken to support this, without essentially recreating huge sections of keystonemiddleware, so think we need to answer two questions before proceeding:

1. Is the workflow I describe above within the intended scope of Commissaire?
2. Should Keystone be supported as an external auth mechanism (gbraad's) model, or pulled into permit both the current 'standalone' operation and as an OpenStack service.

My personal opinion is obviously: Yes, and OpenStack Service; but could work round No and Standalone for my use case by running Commissaire behind a user-facing 'Driver' api that dealt with all of my requirements.

Cheers

**Comment by gbraad** [comment]
@intlabs The reason I choose this way is because of the simplicity. Didn't want to introduce any dependencies, such as keystoneauth, keystonemiddleware, etc... unless really needed. But basically the usecase you describe is the opposite, and make Commissaire an entry in the service catalog, and therefore it would only deal with the token it receives.

**Comment by intlabs** [comment]
@gbraad Both approaches are valid, yours has beauty in its simplicity and gets us going right away (yay!), but I fear may be of limited utility in the long run without ending up replicating a lot of the work that keystonemiddleware does. On the flip side mine gives us all the bells and whistles you could possibly want straight away via well audited and vetted libraries: but requires more up-front work and brings in a load of deps (boo!)  (though if the PR I'm working on to use oslo.log for logging gets accepted, many of these will already be in place).

@ashcrow @mbarnes @gbraad I think it would be great if we could set up a meeting, either on IRC or skype, to discuss the roadmap for Commissaire, not least because I'm concerned that I may have the effect of a "Bull in a china shop" if I'm not sure where Commissaire is trying to go. I'm in Barcelona next week for the OpenStack Conference, but could make time at any point to discuss. It may make more sense, for example, to use Gbraads approach as a 'built-in' and for me to produce a sperate plugin/commissaire service that makes use of keystone middleware.

**Comment by ashcrow** [comment]
> It may make more sense, for example, to use Gbraads approach as a 'built-in' and for me to produce a separate plugin/commissaire service that makes use of keystone middleware.

This is what I was thinking after going through this thread. I see both as being very helpful in different areas. As noted, both are valid and helpful and both would be accepted as long as neither tied us to OpenStack as a general requirement for Commissaire.

The approach @gbraad is taking is our traditional backend system and would help folks who have want to use commissaire, have keystone already, and don't want to have to have yet another authN system in their infrastructure. These could classes such as ```KeystonePasswordAuth```, ```KeystoneTokenAuth```, etc..

The approach @intlabs is taking with ``keystonemiddleware`` sounds like it would be very helpful for those who want to use Commissaire as part of the OpenStack sphere. This could be a class such as ```KeystoneMiddlewareAuth``` since it seems like the middleware itself is true WSGI just like we are utilizing. I'll open a new issue for this work and reference back to this one.

**Comment by ashcrow** [comment]
>  I think it would be great if we could set up a meeting, either on IRC or skype, to discuss the roadmap for Commissaire 

I think starting off with an IRC meeting would be a good idea. It may be a little hard getting everyone in at an acceptable time being that we are spanning US Eastern, Central, Chinese Standard Time, and Barcelona .

https://www.timeanddate.com/worldclock/meetingtime.html?iso=20161024&p1=33&p2=179&p3=31

If we can find a time that works for (@gbraad and @intlabs and (@mbarnes or @ashcrow)) on October 24th that would be great.

> not least because I'm concerned that I may have the effect of a "Bull in a china shop" if I'm not sure where Commissaire is trying to go. 

:laughing: Don't worry about being a "Bull in a china shop". If it starts to feel that way I promise someone will speak up ... and I'd rather people feel free to propose ideas and get feedback in an honest **and** courteous way :smile:.

**Comment by gbraad** [comment]
@intlabs I will not be able to attend the Summit this time, but as suggested by @ashcrow, we could do an IRC or VoIP call if needed. I am fine with the suggested date. But might be an idea to use an online scheduling app? Although I like what @intlabs proposes, I am also slightly hesitant. Yes, these libraries are vetted, many years of development, but they come with a large amount of dependencies that make this project feel like it should have been part of OpenStack ;-)

**Comment by ashcrow** [comment]
See you fellas Monday (tomorrow) in #atomic @:

- China - 8:30 PM
- Barcelona - 2:30 PM 
- UTC - 12:30 PM 
- EST - 8:30 AM
- CST - 7:30 AM

**Comment by ashcrow** [comment]
This is resolved in #29
